SELECT * FROM EMPLOYEE_COPY;

DELETE FROM EMPLOYEE_COPY
WHERE EMP_ID = (SELECT EMP_ID FROM EMPLOYEE_COPY WHERE EMP_NAME= '전형돈' AND SALARY = 2000000);
ROLLBACK;


CREATE TABLE MEMBER_TEST
(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30)
);

INSERT INTO MEMBER_TEST
VALUES(1,'user11','1111','홍길동');

INSERT INTO MEMBER_TEST
VALUES(2,'user22','2222','김말똥');

INSERT INTO MEMBER_TEST
VALUES(3,'user33','3333','고길똥');


CREATE TABLE MEMBER_FOREIGN(
    USER_ID VARCHAR2(20),
    REGDATE DATE,
    FOREIGN KEY (USER_ID) REFERENCES MEMBER_TEST(USER_ID)
);

INSERT INTO MEMBER_FOREIGN
VALUES('user11',SYSDATE);

INSERT INTO MEMBER_FOREIGN
VALUES('user22',SYSDATE);

INSERT INTO MEMBER_FOREIGN
VALUES('user33',SYSDATE);


SELECT * FROM MEMBER_TEST;
SELECT * FROM MEMBER_FOREIGN;

DELETE FROM MEMBER_TEST
WHERE USER_ID = 'user11';

-- 제약조건 확인
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS -- 만든
WHERE TABLE_NAME = 'MEMBER_FOREIGN'
UNION
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS --  제약 조건을 가진 열에 대한 정보 테이블
WHERE TABLE_NAME = 'MEMBER_FOREIGN'
ORDER BY 3 DESC;

-- 제약조건 비활성화
ALTER TABLE MEMBER_FOREIGN
DISABLE CONSTRAINT SYS_C007126;

-- 제약조건 활성화
ALTER TABLE MEMBER_FOREIGN
ENABLE CONSTRAINT SYS_C007126;

DELETE FROM MEMBER_FOREIGN WHERE USER_ID = 'user11';

SELECT * FROM MEMBER_FOREIGN;

ROLLBACK;

TRUNCATE TABLE MEMBER_FOREIGN;


--- 1번 ---
CREATE TABLE KHACADEMY(
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(20),
    PASS VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    NICKNAME VARCHAR2(20) UNIQUE ,
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')),
    TEL VARCHAR2(20) DEFAULT '010-0000-0000',
    ADDRESS VARCHAR2(90)
);

DROP TABLE  KHACADEMY;
--- 2번 ---
INSERT INTO KHACADEMY VALUES(1,'hong11','1234','홍길동','동해번쩍','M','010-4958-2333','경기도');
INSERT INTO KHACADEMY VALUES(2,'gogo11','4444','고길똥','둘리세퀴','M',DEFAULT,'경상도');
INSERT INTO KHACADEMY VALUES(3,'kimDDong','6658','김말똥','내눈은말똥','F','010-6674-8986','전라도');
INSERT INTO KHACADEMY VALUES(4,'sin','5356','신구','니들이게맛을','M','010-8997-1122','울릉도');
INSERT INTO KHACADEMY VALUES(5,'mslove','5555','김민수','영원한ms','F',DEFAULT,'서울시');
INSERT INTO KHACADEMY VALUES(6,'msSDFlove','6666','김S민수','영DF원한ms','F',DEFAULT,'서울시');
--- 3번 ---
UPDATE KHACADEMY 
SET PASS = '9999'
WHERE NICKNAME = '내눈은말똥';

SELECT * FROM KHACADEMY;

--- 4번 ---
UPDATE KHACADEMY
SET TEL = '없음'
WHERE TEL = '010-0000-000';

(SELECT DATA_DEFAULT FROM ALL_TAB_COLS 
            WHERE TABLE_NAME='KHACADEMY' AND COLUMN_NAME='TEL');

ALTER TABLE KHACADEMY MODIFY( TEL VARCHAR2(20) DEFAULT '없음' );

SELECT TEL  FROM KHACADEMY WHERE TEL = TO_LONG_VARCHAR((SELECT DATA_DEFAULT FROM ALL_TAB_COLS 
            WHERE TABLE_NAME='KHACADEMY' AND COLUMN_NAME='TEL'));


--- 5번 ---
DELETE FROM KHACADEMY WHERE ID ='sin';

--- 6번 ---
TRUNCATE TABLE KHACADEMY;



CREATE TABLE MEMBER_TEST01
(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(20),
	USER_PWD CHAR(20)
);

SELECT * FROM MEMBER_TEST01;

-- 이미 생성된 테이블에 새로운 컬럼( 유저이름 : USER_NAME VARCHAR2(20))

ALTER TABLE MEMBER_TEST01 ADD(USER_NAME VARCHAR2(20));

DESC MEMBER_TEST01;

-- 새로운 컬럼 추가 및 DEFAULT 값 설정 
-- (나이 : USER_AGE NUMBER / 기본값 DEFAULT : 0)

ALTER TABLE MEMBER_TEST01 ADD(USER_AGE NUMBER DEFAULT 0);

-- 데이터 삽입
INSERT INTO MEMBER_TEST01 VALUES(1,'USER11','1111','홍길동',DEFAULT);

SELECT  * FROM MEMBER_TEST01;

-- 제약 조건이 없으면 중복된 ID가 저장됨
INSERT INTO MEMBER_TEST01
VALUES(2,'USER11','2222','김말똥',DEFAULT);

-- 테이블의 설정된 제약 조건 확인


-- 제약조건추가
-- 형식
-- ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건 이름 제약조건(컬럼)
ALTER TABLE MEMBER_TEST01
ADD CONSTRAINT MEMBER_ID_UNQ UNIQUE( USER_ID);

-- 제약조건 확인
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS -- 만든
WHERE TABLE_NAME = 'MEMBER_TEST01'
UNION
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS --  제약 조건을 가진 열에 대한 정보 테이블
WHERE TABLE_NAME = 'MEMBER_TEST01'
ORDER BY 3 DESC;

-- NOT NULL 제약 조건을 추가할때에는 ADD 가 아닌 MODIFY로 해야함

ALTER TABLE MEMBER_TEST01
MODIFY USER_PWD CONSTRAINT MEMBER_PWD_NN NOT NULL;

-- 컬럼명 수정
-- USER_PWD -> PASSWORD

ALTER TABLE MEMBER_TEST01
RENAME COLUMN USER_PWD TO PASSWORD;

SELECT * FROM MEMBER_TEST01;

-- 컬럼의 데이터 타입 수정
-- USER_NAME VARCHAR2(20) -> CHAR(30)

ALTER TABLE MEMBER_TEST01
MODIFY USER_NAME CHAR(30);

DESC MEMBER_TEST01;

--DEFAULT 값 수정
-- USER_AGE의 DEFAULT 값 수정( 0->99)

ALTER TABLE KHACADEMY MODIFY( TEL VARCHAR2(20) DEFAULT '없음' );
ALTER TABLE MEMBER_TEST01 MODIFY USER_AGE DEFAULT 99;

-- 컬럼 삭제
-- USER_AGE 컬럼 삭제

ALTER TABLE MEMBER_TEST01
DROP COLUMN USER_AGE;

DESC MEMBER_TEST01;

-- 간단 예제
-- MEMBER_TEST 테이블의 USER_ID 를
-- MEMBER_FOREIGN 테이블에서 참조(외래키 설정)하고 있을때
-- MEMBER_TEST 테이블에서 USER_ID를 삭제 하고 싶을때.


-- 해당 컬럼을 삭제할 때 제약조건이 연결되어 있다면
-- 해당 제약조건도 모ㅜ 삭제하면서 컬럼을 지구은 SQL
ALTER TABLE MEMBER_TEST
DROP COLUMN USER_ID CASCADE CONSTRAINTS;

-- 제약 조건 삭제
-- 설정되어 있는 제약 조건을 삭제 할수 있음.

-- MEMBER_TEST01 테이블에 설정된 UNIQUE 제약 조건 삭제
ALTER TABLE MEMBER_TEST
DROP CONSTRAINT MEMBER_ID_UNQ;

-- 제약 조건 이름 변경
-- 설정되어 있는 제약조건의 이름을 변경 할 수 있음.
ALTER TABLE MEMBER_TEST01
RENAME CONSTRAINT SYS_C007136 TO MEMBER_NO_PK;

-- 테이블 이름변경
-- 생성된 테이블의 이름 변경이 가능함
ALTER TABLE MEMBER_TEST RENAME TO MEMBER_TEST_TBL;

-- 테이블 삭제
-- DROP 명령어를 통해 테이블 삭제가 가능함
DROP TABLE MEMBER_TEST_TBL;
-- 혹은
DROP TABLE MEMBER_TEST_TBL CASCADE CONSTRAINTS;

CREATE TABLE COFFEE
(
    PRODUCT_NAME VARCHAR2(20) PRIMARY KEY,
    PRICE NUMBER NOT NULL,
    COMPANY VARCHAR2(20) NOT NULL
);

INSERT INTO COFFEE VALUES('맥심커피', 30000, 'MAXIM');
INSERT INTO COFFEE VALUES('카누커피', 50000, 'MAXIM');
INSERT INTO COFFEE VALUES('네스카페커피', 40000, 'NESCAFE');

COMMIT;

SELECT * FROM COFFEE;




















