
------------------실습------------------

CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_USERID VARCHAR(20) UNIQUE NOT NULL,
    MEMBER_USERPWD VARCHAR(20) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_GENDER NVARCHAR2(1) CHECK (MEMBER_GENDER IN('남','여')),
    MEMBER_EMAIL VARCHAR(30) NOT NULL
);

INSERT INTO M VALUES( MEM_NO_SEQ.NEXTVAL,'USERID01','PASS001','U1','남','USER01@IEI.OR.KR');
INSERT INTO M VALUES( MEM_NO_SEQ.NEXTVAL,'USERID02','PASS002','U2','여','USER02@IEI.OR.KR');
INSERT INTO M VALUES( MEM_NO_SEQ.NEXTVAL,'USERID03','PASS003','U3','남','USER03@IEI.OR.KR');
INSERT INTO M VALUES( MEM_NO_SEQ.NEXTVAL,'USERID04','PASS004','U4','여','USER04@IEI.OR.KR');
INSERT INTO M VALUES( MEM_NO_SEQ.NEXTVAL,'USERID05','PASS005','U5','남','USER05@IEI.OR.KR');
INSERT INTO M VALUES( MEM_NO_SEQ.NEXTVAL,'USERID06','PASS006','U6','여','USER06@IEI.OR.KR');

CREATE SEQUENCE MEM_NO_SEQ
START WITH 1000
INCREMENT BY 1
MAXVALUE 1000000
NOCYCLE
NOCACHE;

CREATE TABLE BOARD
(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(20) NOT NULL,
    BOARD_CONTENT VARCHAR2(200) NOT NULL,
    BOARD_WRITEDATE DATE NOT NULL,
    BOARD_NICKNAME VARCHAR2(20) NOT NULL,
    FOREIGN KEY(BOARD_NICKNAME) REFERENCES MEMBER (MEMBER_NICKNAME)
);

INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, 'TITLE01','CONTENT01',SYSDATE,'U1');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, 'TITLE02','CONTENT02',SYSDATE,'U2');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, 'TITLE03','CONTENT03',SYSDATE,'U3');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, 'TITLE04','CONTENT04',SYSDATE,'U4');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, 'TITLE05','CONTENT05',SYSDATE,'U5');
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, 'TITLE06','CONTENT06',SYSDATE,'U6');

CREATE SEQUENCE BOARD_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 500000
NOCYCLE
NOCACHE;

CREATE VIEW BOARD_VIEW
AS SELECT MEMBER_NO AS 회원번호, MEMBER_NICKNAME AS 회원닉네임, MEMBER_EMAIL AS 회원이메일, BOARD_TITLE AS 회원작성글제목
FROM MEMBER M JOIN BOARD B ON (M.MEMBER_NICKNAME = B.BOARD_NICKNAME);
          
CREATE INDEX BOARD_INDEX ON BOARD(BOARD_TITLE,BOARD_CONTENT);

DROP TABLE BOARD;
DROP VIEW BOARD_VIEW;
DROP SEQUENCE BOARD_NO_SEQ;
SELECT * FROM B;
SELECT * FROM M;
SELECT * FROM BOARD_VIEW;
SELECT * FROM BOARD_INDEX;

SELECT * FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'BOARD_INDEX';
