SELECT EMP_NAME, LENGTH(EMP_NAME), LENGTHB(EMP_NAME)
FROM EMPLOYEE;

SELECT INSTR('Hello World Hi High','H',-1,1) FROM DUAL;

SELECT INSTR(EMAIL,'@') AS "@위치" FROM EMPLOYEE;

SELECT LPAD('mslove',20,'#') FROM DUAL;

SELECT LPAD(EMAIL, 20,' ') FROM EMPLOYEE;

SELECT RPAD(EMAIL, 20, ' ') FROM EMPLOYEE;

SELECT LTRIM('00000000000000KHLOVE0','0') FROM DUAL;

SELECT LENGTH(LTRIM('____KHLOVE','_')) FROM DUAL;

SELECT LTRIM('123KH', '1') FROM DUAL;

SELECT LTRIM('12312123231KH','123') FROM DUAL;

SELECT RTRIM('KH12312123231','11312312323') FROM DUAL;

SELECT TRIM('  KH    ') FROM DUAL;
    --- CHAR 를 작성하지 않으면 기본적으로 공백을 삭제하라는 의미
    --- 위치( 앞 또는 뒤)를 지정하지 않으면 기본적으로 BOTH(양쪽) 값을 가지고 잇음

SELECT TRIM('Z' FROM 'ZZKHZZ') FROM DUAL;
SELECT TRIM(LEADING 'Z' FROM 'ZZKHZZ') FROM DUAL;
SELECT TRIM(TRAILING 'Z' FROM 'ZZKHZZ') FROM DUAL;
SELECT TRIM(BOTH 'Z' FROM 'ZZKHZZ') FROM DUAL;

-- 실습 문제 1
-- Hello KH Java 문자열을 Heloo KH 가 출력되게 하여라.
SELECT RTRIM ('Hello KH Java' ,'Java') FROM DUAL;

-- 실습 문제 2
-- Hello KH Java 문자열을 KH Java 가 출력되게 하여라.
SELECT LTRIM ('Hello KH Java' ,'Helo') FROM DUAL;


-- 실습 문제 3 (TRIM으로 해보세요)
-- DEPARTMENT 테이블에서 DEPT_TITME을 출력하여라
-- 이때, 마지막 부 글자를 빼고 출력되도록 하여라 / ex)회계관리부 -> 회계관리

SELECT TRIM (TRAILING '부' FROM DEPT_TITLE) FROM DEPARTMENT;

-- 실습 문제 4
-- 다음문자열에서 앞뒤 모든 숫자를 제거하세요.
-- '982341678934509hello89798739273402'
SELECT LTRIM(RTRIM('982341678934509hello89798739273402','0123456789'),'0123456789') FROM DUAL;




SELECT SUBSTR('SHOW ME THE MONEY',6,2) FROM DUAL;
SELECT SUBSTR('SHOW ME THE MONEY',6) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY',-8,3) FROM DUAL;
SELECT SUBSTR('쇼미더머니',2,2) FROM DUAL;

SELECT EMP_NAME,SUBSTR(EMP_NO,1,6) FROM EMPLOYEE;

--@ 실습문제1
--- 사원명에서 성만 중복없이 사전순으로 출력하세요.
SELECT DISTINCT(SUBSTR(EMP_NAME,1,1)) FROM EMPLOYEE
ORDER BY 1;

--@실습문제 2
---- EMPLOYEE 테이블에서 남자만 사원번호, 사원명, 주민번호, 연봉을 나타내세요.
---- 주민번호의 뒷 6자리는 * 처리하세요.
SELECT EMP_ID,EMP_NAME, RPAD(SUBSTR(EMP_NO,1,8),14,'*'), SALARY*12 FROM EMPLOYEE
WHERE EMP_NO LIKE '_______1%';
--WHERE SUTSTR(EMP_NO,8,1) IN('1','3');

SELECT INITCAP('Welcom To My Oracle World') FROM DUAL;
SELECT INITCAP('Welcom To My Oracle World') FROM DUAL;
SELECT INITCAP('WELCOM TO MY ORACLE WORLD') FROM DUAL;

SELECT CONCAT('가나다','ABC') FROM DUAL;
SELECT '가나다'||'ABC'||'DEF' FROM DUAL;

SELECT REPLACE('Hello World','Hello','Java') FROM DUAL;

-- @실습문제
-- EMPLOYEE 테이블의 모든 직원의 이름 , 주민번호, EMAIL을 출력하시오
-- 단 출력시 EMAIL은 kh.or.kr.에서 iei.or.kr로 변경하여 출력되게 하시오

SELECT EMP_NAME, EMP_NO,REPLACE(EMAIL,'kh.or.kr','iei.or.kr') AS 이메일 FROM EMPLOYEE;

SELECT MOD(10,3) FROM DUAL;

SELECT ROUND(123.456,2) FROM DUAL;
SELECT ROUND(123.456,1) FROM DUAL;
SELECT ROUND(123.456,0) FROM DUAL;
SELECT ROUND(123.456,-1) FROM DUAL;
SELECT ROUND(123.456,-2) FROM DUAL;

SELECT TRUNC(123.456,2) FROM DUAL;
SELECT TRUNC(123.456,1) FROM DUAL;
SELECT TRUNC(123.456,0) FROM DUAL;
SELECT TRUNC(123.456,-1) FROM DUAL;
SELECT TRUNC(123.456,-2) FROM DUAL;


SELECT CURRENT_DATE FROM DUAL;

SELECT LOCALTIMESTAMP FROM DUAL;

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT EMP_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE , HIRE_DATE))AS 개월, 
HIRE_DATE,SYSDATE FROM EMPLOYEE;

SELECT EMP_NAME,HIRE_DATE, ADD_MONTHS(HIRE_DATE,6)
FROM EMPLOYEE;

SELECT SYSDATE AS "싸이 재입대일", ADD_MONTHS(SYSDATE, 18) AS "전역일", FLOOR(ADD_MONTHS(SYSDATE, 18) - SYSDATE) * 3 AS "남은 짬밥수" FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'수요일') FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'수') FROM DUAL;

SELECT NEXT_DAY(SYSDATE,4) FROM DUAL;

SELECT LAST_DAY('09/01/01') FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;

-- @ 실습문제 1
-- EMPLOYEE 테이블에서 사원의 이름,입사일,년차를 출력하여라. 
-- 단, 입사일은 YYYY년M월D일로 출력하도록 하여라.
-- 년차 출력은 소수점 일경우 올림으로 하여 출력하여라. (28.144 -> 29년차)
-- (출력시 정렬은 입사일 기준으로 오름차순)
SELECT EMP_NAME AS 이름, EXTRACT(YEAR FROM HIRE_DATE)|| '년' || EXTRACT(MONTH FROM HIRE_DATE) || '월' ||EXTRACT(DAY FROM HIRE_DATE) || '일' AS 입사일,
CEIL((SYSDATE - HIRE_DATE)/365) AS 년차 FROM EMPLOYEE
ORDER BY HIRE_DATE;



-- @ 실습문제 2
-- 특별 보너스를 지급하기 위하여 자료가 필요하다
-- 입사일을 기점으로 다음달 1일 부터 6개월을 계산하여 
-- 출력하시오 (이름,입사일,기준일,기준일+6,기준달(월))
-- ex) 90년2월6일 입사 -> 90년3월1일 부터 계산
-- ex) 90년2월26일 입사 -> 90년3월1일 부터 계산
-- ex) 97년12월1일 입사 -> 98년1월1일 부터 계산
-- 출력시 입사일 기준으로 정렬하시오

SELECT EMP_NAME AS 이름, HIRE_DATE AS 입사일, LAST_DAY(HIRE_DATE)+1 AS 기준일, 
ADD_MONTHS(LAST_DAY(HIRE_DATE)+1, 6) AS "기준일 + 6", EXTRACT(MONTH FROM  ADD_MONTHS(LAST_DAY(HIRE_DATE)+1,6)) || '월' AS "기준달(월)" 
FROM EMPLOYEE
ORDER BY HIRE_DATE;


SELECT TO_CHAR(SYSDATE,'YYYY"년"MM"월"DD"일"HH"시"SS"초"AM') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD-DAY') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD-HH-SS-AM') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD/PMHH12"시"MI"분"SS"초"') FROM DUAL;


SELECT EMP_NAME AS 사원명, TO_CHAR(HIRE_DATE,'YYYY/MM/DD(DY)') AS 고용일 FROM EMPLOYEE ;

SELECT TO_CHAR(1000000,'999,999,999') FROM DUAL;
SELECT TO_CHAR(1000000,'000999,999,999') FROM DUAL;
SELECT TO_CHAR(1000000,'$999,999,999') FROM DUAL;
SELECT TO_CHAR(1000000,'L999,999,999') FROM DUAL;

SELECT TO_DATE(20010101,'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE(20010101,'YYYY/MM/DD'),'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(TO_DATE(20010101,'YYYY/MM/DD'),'YYYY/MM/DD HH24:MI:SS(DY)') FROM DUAL;

SELECT TO_CHAR(TO_NUMBER('10,000,000','99,999,999') - TO_NUMBER('23'),'999,999,999,999') FROM DUAL;

SELECT TO_NUMBER('A1,000,000','999,999,999,999') FROM DUAL;  -- 에러 : 유효한 숫자 입력
SELECT TO_NUMBER('$1,000,000','999,999,999,999') FROM DUAL;  -- 에러 : $형식 인식 불가
SELECT TO_NUMBER('$1,000,000','$999,999,999,999') FROM DUAL; -- 정상

SELECT NVL(BONUS, '0') FROM EMPLOYEE;

SELECT EMP_NAME, DECODE(SUBSTR(EMP_NO,8,1), '1','남자','여자') FROM EMPLOYEE;

SELECT EMP_NAME, EMP_NO FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,1,2) BETWEEN 60 AND 69;

SELECT EMP_NAME AS 이름,DECODE(SUBSTR(EMP_NO,1,2),
        '61','소띠',
        '62','호랑이띠',
        '63','토끼띠',
        '64','용띠',
        '65','뱀띠',
        '66','말띠',
        '67','양띠',
        '68','원숭이띠',
        '69','닭띠') AS 띠
        FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,1,2) BETWEEN 60 AND 69;


SELECT EMP_NAME, CASE WHEN SUBSTR(EMP_NO,8,1) = 1 THEN '남자'
                      WHEN SUBSTR(EMP_NO,8,1) = 2 THEN '여자'
                     END AS 성별
FROM EMPLOYEE;
                
                
SELECT EMP_NAME, CASE WHEN SUBSTR(EMP_NO,3,2) BETWEEN 3 AND 5 THEN '봄 태생'
                      WHEN SUBSTR(EMP_NO,3,2) BETWEEN 6 AND 8 THEN '여름 태생'
                      WHEN SUBSTR(EMP_NO,3,2) BETWEEN 9 AND 11 THEN '가을 태생'
                      ELSE '겨울 태생'
                      END AS "출생 계절"
FROM EMPLOYEE;


SELECT SUM(SALARY) AS 직원월급총합 FROM EMPLOYEE;
SELECT AVG(SALARY) AS 직원월급평균 FROM EMPLOYEE;
SELECT SUM(SALARY), COUNT(*) AS 직원수 FROM EMPLOYEE;

SELECT MIN(SALARY),MAX(SALARY) FROM EMPLOYEE;